version: '3.8'
services:
  postgres:
    container_name: film-catalog
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: userPostgres
      POSTGRES_PASSWORD: passDocker
      POSTGRES_DB: film-catalog
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
